=== Arviiin/FastForm/nextone.fastform.core/src/main/java/nextone/fastform/xml/EntityBean.xsd
<?xml version="1.0" encoding= "UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="http://www.pfu.cn"
xmlns="http://www.pfu.cn"
elementFormDefault="qualified">
	<xs:element name="EntityBean">
		<xs:complexType>
				<xs:all>
				<xs:element name="entityId" type="xs:string" maxOccurs="1"/>
				<xs:element name="pojoNm" type="xs:string" maxOccurs="1"/>
				<xs:element name="bizKey" type="xs:string" maxOccurs="1"/>
				<xs:element name="sequenceNm" type="xs:string" maxOccurs="1"/>
				<xs:element name="fields">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="field" minOccurs="1" maxOccurs="unbounded">
								<xs:complexType>
									<xs:all>
										<xs:element name="inputType" type="xs:string" minOccurs="0" maxOccurs="1" />
										<xs:element name="hidAttributePath" type="xs:string"  minOccurs="0" maxOccurs="1"/>
										<xs:element name="hidAttributeId" type="xs:string" minOccurs="0" maxOccurs="1"/>
										<xs:element name="precision" type="xs:int" minOccurs="0" maxOccurs="1"/>
										<xs:element name="scale" type="xs:int" minOccurs="0" maxOccurs="1"/>
										<xs:element name="nameType" type="xs:string" minOccurs="0" maxOccurs="1"/>
										<xs:element name="maxlength" type="xs:integer" minOccurs="0" maxOccurs="1"/>
										<xs:element name="nullable" type="xs:boolean" minOccurs="0" maxOccurs="1"/>
										<xs:element name="labelMsgCd" type="xs:string" minOccurs="0" maxOccurs="1"/>
										<xs:element name="must" type="xs:boolean" minOccurs="0" maxOccurs="1"/>
										<xs:element name="unique" type="xs:boolean" minOccurs="0" maxOccurs="1"/>
										<xs:element name="upperCase" type="xs:boolean" minOccurs="0" maxOccurs="1"/>
										<xs:element name="enableFullWidthChar" type="xs:boolean" minOccurs="0" maxOccurs="1"/>
										<xs:element name="readOnly" type="xs:string" minOccurs="0" maxOccurs="1"/>
										<xs:element name="onValueTransl" type="xs:string" minOccurs="0" maxOccurs="1"/>
										<xs:element name="offValueTransl" type="xs:string" minOccurs="0" maxOccurs="1"/>
										<xs:element name="onText" type="xs:string" minOccurs="0" maxOccurs="1"/>
										<xs:element name="offText" type="xs:string" minOccurs="0" maxOccurs="1"/>
										<xs:element name="typeCd" type="xs:string" minOccurs="0" maxOccurs="1"/>
										<xs:element name="lblValBeanService" type="xs:string" minOccurs="0" maxOccurs="1"/>
										<xs:element name="manyToOne" type="xs:string" minOccurs="0" maxOccurs="1"/>
										<xs:element name="oneToMany" type="xs:string" minOccurs="0" maxOccurs="1"/>
									</xs:all>
									<xs:attribute name="fieldName" type="xs:string" use="required" />
									<xs:attribute name="fieldType" type="xs:string"  use="required"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				</xs:all>
				<xs:attribute name="entityname" type="xs:string" />
				<xs:attribute name="EntityBeanxmlpath" type="xs:string" />
				<xs:attribute name="extendsBaseEntity" type="xs:string" />
		</xs:complexType>
	</xs:element>
	
</xs:schema>

=== Arviiin/FastForm/nextone.fastform.core/src/main/java/nextone/fastform/xml/StudentBean.xml
<?xml version="1.0" encoding="UTF-8"?>
<EntityBean xmlns="http://www.psh.com.cn" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.psh.com.cn EntityBean.xsd" 
	entityName="nextone.master.bean.StudentBean"
	extendsEntity="nextone.master.bean.BaseEntityBean">
	<entityId>stuId</entityId>
	<pojoNm>Dmt020</pojoNm>
	<bizKey>stuCd</bizKey>
	<sequenceNm>DMT020SQ01</sequenceNm>
	<fields>
		<field  name="stuId">
		    <inputType>HIDDEN</inputType>
			<hidAttributePath>studentBean.stuId</hidAttributePath>
			<hidAttributeId>hidStuId</hidAttributeId>
			<precision>8</precision>
			<scale>0</scale>
		</field>
		<field  name="stuCd">
			<inputType>CODE</inputType>
			<maxlength>20</maxlength>
			<must>true</must>
    		<upperCase>true</upperCase>
    		<labelMsgCd>stuCd</labelMsgCd>
    	</field>
    	<field  name="stuNm">
    		<inputType>TEXT</inputType>
			<maxlength>40</maxlength>
			<must>true</must>
    		<labelMsgCd>stuNm</labelMsgCd>
    	</field>
    	<field  name="stuSex">
    		<inputType>SWITCH</inputType>
			<onValueTransl>1</onValueTransl>
			<offValueTransl>0</offValueTransl>
    		<onText>label.male</onText>
    		<offText>label.female</offText>
    		<labelMsgCd>stuSex</labelMsgCd>
    		<maxlength>20</maxlength>
    	</field>
    	<field  name="stuAge">
    		<inputType>NUM</inputType>
			<maxlength>2</maxlength>
			<must>true</must>
			<precision>8</precision>
			<scale>0</scale>
    		<labelMsgCd>stuAge</labelMsgCd>
    	</field>
    	<field  name="stuMotherLang">
    		<inputType>SELECT</inputType>
			<maxlength>20</maxlength>
			<typeCd>001</typeCd>
    		<labelMsgCd>stuMotherLang</labelMsgCd>
    	</field>
   		<field  name="stuDesc">
   			<inputType>MULTLANG</inputType>
			<maxlength>40</maxlength>
			<must>true</must>
    		<labelMsgCd>stuDesc</labelMsgCd>
    		<nameType>200</nameType>
    		<unique>true</unique>
    	</field>
	</fields>
</EntityBean>
